import { Link } from 'react-router-dom'
import { LineChart } from 'lucide-react'

export default function Footer() {
  return (
    <footer className="mt-auto border-t border-white/[0.06] py-2">
      <div className="mx-auto flex max-w-[88rem] items-center justify-between gap-3 px-4 sm:px-6 lg:px-8">
        <Link to="/" className="flex items-center gap-2">
          <span className="flex h-6 w-6 items-center justify-center rounded-md bg-amber/15 text-amber">
            <LineChart size={14} strokeWidth={2.25} />
          </span>
          <span className="font-display text-sm font-semibold text-paper">InvestIQ</span>
        </Link>
        <p className="text-center text-xs text-mist/70">
          Research is generated by AI and is not investment advice. © {new Date().getFullYear()} InvestIQ, Inc.
        </p>
      </div>
    </footer>
  )
}
